import { Inter } from "next/font/google";
import "../styles/globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      {/* <Head>
        <link rel="icon" href="/public/assets/icons/icon-pokeball-16.png" />
      </Head> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
